name: redux_scopedmodel_bloc
description: Companion Source Code

version: 1.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_redux:
  scoped_model:
  rxdart: 
  flutter_sparkline:
  cupertino_icons:


flutter:

  uses-material-design: true
